### ISSUE TITLE
Add a switch to disable logging

### ISSUE THREAD

**Issue by coldiron** [Vittel/RunHiddenConsole#2]
I'm using this to silently run a powershell command in the right-click context menu. In my use case, it creates a log file in whichever directory I run the context item. 

I've built it myself without logging but it'd be great if there was a switch to enable/disable it.

**Comment by SeidChr** [comment]
sounds legit.
will see what i can do.

**Comment by SeidChr** [comment]
just added the option to define the log level in the app.config.
please check if setting the level to "Exception" anything higher than "Info" will cover your case

**Comment by coldiron** [comment]
Works beautifully. Thanks!
