### ISSUE TITLE
Double quotes are not sent to target console.

### ISSUE THREAD

**Issue by RiabikovR** [Vittel/RunHiddenConsole#3]
Whenever RunHiddenConsole receives launch arguments encased in double quotes, such as file paths, it strips double quotes upon sending arguments to the target executable, which breaks arguments that contain spaces.
For example `cmdw.exe "C:\Program Files\someapp.exe"` does not work because of that.

**Comment by SeidChr** [comment]
i have just tried to fix this.
can you verify?

**Comment by RiabikovR** [comment]
Just got an exception `System.InvalidOperationException: 'The key 'LogLevel' does not exist in the appSettings configuration section.'` after compiling.
Does that mean I need to keep the config file present at all times?

**Comment by SeidChr** [comment]
Well, that was unintended, and ill fix it. But this was present for a couple of month now.

**Comment by RiabikovR** [comment]
Even after I renamed App.config to cmdw.exe.config and added it to cmdw.exe, it keeps throwing this exception.
Result is the same even if I try running hiddenw.exe in the output folder, where it has it's own config.

**Comment by SeidChr** [comment]
i have just pushed some new code which changes the readout. 
but i also have never seen that exception, so im not 100% sure if it works now.
let me know..

**Comment by RiabikovR** [comment]
Nope, still nothing.
It doesn't happen in the debugger, only when I run the application outside VS.
Maybe I'm doing something wrong? Could you send me your compiled version?

**Comment by SeidChr** [comment]
lets chat: https://gitter.im/RunHiddenConsole

**Comment by RiabikovR** [comment]
Fixed. Thanks.
