### ISSUE TITLE
Allow to be used anywhere

### ISSUE THREAD

**Issue by Indigo744** [Vittel/RunHiddenConsole#4]
Right now, the requirement is to copy this file to where powershell.exe is.

I cannot ask my users to copy this file in their System directory. I would prefer if this program find powershell automatically, and use it from where it is.

Thanks.

**Comment by SeidChr** [comment]
I am not exactly sure what u ask for.
Do u want an installer?

I guess i could create some script figuring out the location and copy the exe there.
Would this be sufficient?

Or do u want the file to reside in user space and find the target executable from e.g. path?

**Comment by Indigo744** [comment]
Sorry I wasn't more clear.

Basically, I would like to be able to use this tool from any location, like for instance in `D:\Tools` or a network drive (for my team to use) which is mounted on a drive. 

That way, I can embed it into a tool and I don't have to ask to each developers to install this tool in order to be able to use the scripts.

**Comment by Indigo744** [comment]
I mean I understand _why_ you made a generic tool that can work with any name, but I would love a specific one that would always look for `%SystemRoot%\SysWOW64\WindowsPowerShell\v1.0\powershell.exe` (or other [known location](https://www.powershelladmin.com/wiki/PowerShell_Executables_File_System_Locations))

**Comment by SeidChr** [comment]
How would you want to set the location?
To be more specific: how would you want to specify which target executable has to be executed?

**Comment by Indigo744** [comment]
That's the point, I wouldn't have to set the location.

To be more clear, in your code, in `GetTargetExecutablePath()`, instead of using the current assembly name, the tool would look at the [known location of powershell](https://www.powershelladmin.com/wiki/PowerShell_Executables_File_System_Locations), and when it finds the correct one (according to platform version), simply use it.

Thinking about it, I guess it would make sense to do it in a new GitHub project, since it would be a really specific implementation (targeting powershell) instead of a generic purpose tool.

Another possibility, as you said, would be to be able to specify the target executable instead of using the current path and assembly name. I imagine it could be done with a `.config` file or with a special swith on the commandline (preferred), e.g. `hiddenw.exe hiddenwTarget=<path to executable> [other params for the target]`.

**Comment by Indigo744** [comment]
Also, speaking of specifying the target, it would be good to be also able to specify the log location.

**Comment by SeidChr** [comment]
well my first idea was to get the executable name as before, from the current executabele without the "w", but then find the executable with the environment variable "path" instead of the same folder.
But then you still would have to specify the execution directory. 
So adding the hidden console tool into the path itself would be a good idea. this is implicitly done when you put the file next to the original.
It could be put in another location within the user-accessible space of the "path".
you would still have to do that manually (installer/script?).

Changing the commandline parameters is quite delicate, because the tools is especially written to pass all parameters along to the target executable as is. id rather not add any special commandline handling that is filtered out by my proxy. 
Config-File is the best idea for further configuration.
Log-Location shouldn't be a big issue, as logging is already configurable in the config file to a certain degree.

The same way it should be possible to specify multiple locations in the config file, which the proxy is looking in, to find the target executbale.

can you explain your usecase a little better? i made this tool to get rid of a tiny little flashing tool-window. but you seem to develop something more arround it, which i try to make sense of.

**Comment by Indigo744** [comment]
I like the idea of first checking if the _current executable name without the "w"_ is in the current location (current behavior), then checking if it is in the user PATH env then checking the computer PATH env.

That way, it would not modify current behavior for existing user, and still allow this tool to find Powershell (or other) easily.

**My use case is simple**: we have an [InnoSetup](http://www.jrsoftware.org/isinfo.php) script that run some powershell script on each imported files before packaging it into the installer. As you know, with `-windowstyle hidden` we can still see the tiny little flashing blue window. And since the script is called a lot for each file (almost every second) it's really annoying, and prevent from doing any work while InnoSetup script is running (it steals the focus). Hence the need to hide this window. 
I though your tool would be better than a VBScript.
Now the catch is that this InnoSetup script is in a shared drive and anyone can launch it in order to build the installer, and I don't want to have any external dependencies on the developer's computer (like putting your tool alongside powershell in System).
That is why I would prefer a tool that can work from _any_ folder rather than right where the other executable is.

**Comment by SeidChr** [comment]
i have just added the bespoken things:
- log path (configurable in config file)
- path lookup (evaluates the environment path variable)

also i have added an additional variable to be set within the config file, acting as a first-look path variable. it can be used exactly as "PATH" environment variable woud, but paths are checked just before everything else. 
Using it is completely optional. 

Please check whether it fits your needs

**Comment by Indigo744** [comment]
Thanks a lot for working on it.

I'll try to find some time to get the repo and compile it. In the mean time, I've commented directly on the commit.

**Comment by Indigo744** [comment]
I just tested with `powershellw.exe` and it works beautifully. Thank you!

I'll close this issue and wait for an official release now 😉

**Comment by SeidChr** [comment]
@Indigo744 i do not use the release-feature as i propably should. You can happily use the version you have build yourself.
If you require a release just tell me.

**Comment by Indigo744** [comment]
Of course, but I always prefer to use official release.
Also, since I'll write a small documentation, I'll need a link to refer to the release to be downloaded, so anyone can reproduce the setup if need be (without having to get the repo and build it).

And I guess it could interest other users as well!

**Comment by SeidChr** [comment]
there you go :)
https://github.com/Vittel/RunHiddenConsole/releases/tag/1.0.0-alpha.2
