### ISSUE TITLE
would you mind adding a license, please?

### ISSUE THREAD

**Issue by kewalaka** [Vittel/RunHiddenConsole#5]
MIT would be preferred, thanks!

**Comment by SeidChr** [comment]
Do you mind telling me for what reasons you need it?

**Comment by kewalaka** [comment]
Sure, gets flagged from a "use of open source" compliance perspective.
This seems the best alternative for launching PS without a window popping
up  whilst MS sort out a long term solution.  I don't want yo use wscript
hacks, Defender ASRs flag this.  I can write a simple wrapper myself but
figure why re-invent.

**Comment by SeidChr** [comment]
So you want me to put a license on the software, not the code?

**Comment by kewalaka** [comment]
I have an alternative that is mit licensed (source), but I prefer yours.

**Comment by SeidChr** [comment]
sorry this took me a while to 1. remember it and 2. chose one which fits for me
added the mpl2
