### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by wi-ry** [Vittel/RunHiddenConsole#7]
Not an issue, but wanted to say thanks for the utility. I've been trying to find a good way to run scheduled tasks on some pwsh scripts for a while now without the flickering window, and this works great.

Would love to buy you a coffee for your effort!

**Comment by SeidChr** [comment]
> Not an issue, but wanted to say thanks for the utility. I've been trying to find a good way to run scheduled tasks on some pwsh scripts for a while now without the flickering window, and this works great.
> 
> Would love to buy you a coffee for your effort!

Wow, thank you very much! Means allot in these times 😊

No need for coffee, but you can get in contact on mastodon
Chief Posh ☑ (@xeo@dotnet.social)
https://dotnet.social/@xeo
